### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lydiacheah**
To run all RSPEC tests just run `rspec`.
For a specific folder or file: `rspec spec/FOLDER_NAME/FILE_NAME.rb` 
`debugger` and `shoulda-matchers` gems are also added for debugging in the current rails version and for writing cleaner tests. 
Read more about [debugger](https://github.com/cldwalker/debugger) or [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers).

### CODE REVIEW

**Comment by svenaas** [comment]
I'm working on a computer that I hadn't previously used for drxfer so I had no dev environment set up. 

I cloned the repo, switched to this branch, and ran vagrant up. I got

```
`playbook` does not exist on the host: /Users/saas/Projects/drxfer/.ansible/master.yml
```

@jproctor what am I missing? There doesn't seem to be a submodule missing.

**Comment by jproctor** [comment]
Aha! I know what that is.

Because drxfer is a public repo and we didn't know what it would look like on GitHub to have a private submodule in a public repo, we pulled that repo separately into our ~/Projects folder (`git clone saas@spruce.mtholyoke.edu/var/lib/git/ansible-mhc.git` iirc) and then symlinked to it from drxfer/.ansible .

This PR includes our Vagrantfile, because that's how we have been managing projects with VMs. We might actually want to have a conversation about that structure before merging.

**Comment by svenaas** [comment]
But then
screen shot 2017-03-08 at 10 15 28 am

**Comment by svenaas** [comment]
OK, so if you add drxfer.local to `/etc/hosts` _first_ Ansible works. This all ought to be documented somewhere...

**Comment by svenaas** [comment]
@lydiacheah, where are you running rspec?

Inside the VM rspec is not installed (I tried `rspec` and `bundle exec rspec`). I could install it one way or another, but want to be sure we're doing this the same way. And either way it should probably be part of the Ansible playbook, @jproctor. 

Outside the VM I don't happen to have rspec installed either. I can do this in a particular Ruby version's gem set, or (probably better) I could use bundler, but I suspect you're intending this to happen inside the VM.

**Comment by lydiacheah** [comment]
@svenaas `rspec` is a gem so I believe that you will have to use bundler. `bundle install` should fix it, don't think I did it any other way.

**Comment by svenaas** [comment]
No luck: 

```
$ vagrant ssh
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-65-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

1 package can be updated.
0 updates are security updates.


*** System restart required ***
Last login: Thu Mar  9 11:17:47 2017 from 10.0.2.2
ubuntu@ubuntu-xenial:~$ cd /vagrant
ubuntu@ubuntu-xenial:/vagrant$ bundle install
Fetching gem metadata from http://rubygems.org/...............
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Rubygems 1.8.23 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Installing rake 10.0.3
Installing multi_json 1.7.2
Installing builder 3.0.4
Installing i18n 0.6.4
Installing erubis 2.7.0
Installing rack 1.3.10
Installing hike 1.2.1
Installing tilt 1.3.6
Installing mime-types 1.22
Installing polyglot 0.3.3
Installing arel 2.2.3
Installing tzinfo 0.3.37
Installing bcrypt-ruby 3.0.1 with native extensions
Installing highline 1.6.16
Installing net-ssh 2.6.6
Installing coffee-script-source 1.6.2
Installing json 1.7.7 with native extensions
Installing thor 0.14.6
Installing columnize 0.9.0
Installing debugger-linecache 1.2.0
Installing debugger-ruby_core_source 1.3.8
Installing orm_adapter 0.4.0
Installing net-ldap 0.2.2
Installing diff-lcs 1.2.2
Installing mini_portile2 2.1.0
Installing nested_form 0.2.3
Installing pg 0.15.0 with native extensions
Using bundler 1.14.6
Installing rspec-core 2.13.1
Installing rspec-mocks 2.13.0
Installing sass 3.2.7
Installing sqlite3 1.3.7 with native extensions
Installing activesupport 3.1.12
Installing execjs 1.4.0
Installing rack-cache 1.2
Installing rack-mount 0.8.3
Installing rack-test 0.6.2
Installing rack-ssl 1.3.3
Installing warden 1.2.1
Installing sprockets 2.0.4
Installing treetop 1.4.12
Installing net-scp 1.1.0
Installing net-sftp 2.1.1
Installing net-ssh-gateway 1.2.0
Installing rdoc 3.12.2
Installing debugger 1.6.8 with native extensions
Installing rspec-expectations 2.13.0
Installing nokogiri 1.6.8.1 with native extensions
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native
extension.

        /home/ubuntu/.rbenv/versions/1.9.2-p290/bin/ruby extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/ubuntu/.rbenv/versions/1.9.2-p290/bin/ruby
	--with-pg
	--without-pg
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config


Gem files will remain installed in
/home/ubuntu/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/pg-0.15.0 for
inspection.
Results logged to
/home/ubuntu/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/pg-0.15.0/ext/gem_make.out

An error occurred while installing pg (0.15.0), and Bundler cannot
continue.
Make sure that `gem install pg -v '0.15.0'` succeeds before bundling.
```

**Comment by lydiacheah** [comment]
That is really strange. I didn't have this problem before we switched to PostgreSQL (I did on my current local branch after switching). Would this have something to do with the VM or Ansible?

**Comment by svenaas** [comment]
Maybe @jproctor can give it a try on his machine before your next shift on March 20 (during which shift I'll be at the eye doctor, though I'll be around for most of your March 21 shift).

**Comment by jproctor** [comment]
This code is only meaningful against what is now the [**rails3.1** branch](https://github.com/mtholyoke/drxfer/tree/rails3.1), as the debugger gem doesn’t work in Ruby 2.0+.

I am closing this PR but not deleting the [**testing** branch](https://github.com/mtholyoke/drxfer/tree/testing), in case we want to fix its dependencies or reuse parts of it after we’ve modernized the rest of the platform.

**Pull request closed without merging**
