### PR TITLE
Allow multiple file selection

### PR DESCRIPTION
**Pull request by lydiacheah**
Added support to select multiple files through [CarrierWave](https://github.com/carrierwaveuploader/carrierwave#multiple-file-uploads). 

Multiple files in a folder (not folders themselves) can now be selected, but the option to add a new file from a different folder is also still available. 

For example, if files from `test_folder_1` are selected, then files from `test_folder_2` cannot be selected. Users must click on 'Add file' to select files from other folders. 

image

All tests should pass when `rspec` is run.

### CODE REVIEW

**Comment by svenaas** [comment]
Shaun and Leslie have both weighed in on this:

Shaun:
> I watched the video from Lydia, and I think it is definitely an improvement. I thought about the selection of subfolders issue and I don't think it will be a problem, since this method still requires you to select the files within the folder you'd like to upload. In other words, you actually can't select just a folder and hit 'upload', so there would be no way for users to accidentally think they are uploading a subfolder when they aren't. The notice of the number of files uploaded helps with that as well. All in all, I think this is a nice step forward for making drxfer more friendly.
> 
> Thanks for working on this!

Leslie:
> I agree with Shaun that this multiple file update is clear. The folder issue also seems clear, especially because the user won't be able to simply select a folder and upload it.
> 
> This also is where the ASC interaction will be especially important so we can walk individuals through these steps after they've requested information about transferring files and after we've set up a "donor agreement" in the transfer system as well. 
>
> Many thanks to Lydia!

Indeed. Thank you, @lydiacheah!

**Comment by svenaas** [comment]
@lydiacheah, on Wednesday or when you are next ready for a new task could you please merge the newer stuff on master into this branch and make sure things are still good?

**Comment by lydiacheah** [comment]
Great! Will do. :)

**Comment by lydiacheah** [comment]
Merged and tests are passing!

**Comment by svenaas** [comment]
Looks good. Thanks, @lydiacheah!

**Pull request merged**
